version: '3'
services: 
  api-solid-pg: 
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid


# TENDO ESSE DOCKER COMPOSE -> Só rodar docker compose up -d na raiz do projeto
# PARA PARAR -> docker compose stop
# PARA DELETAR O CONTAINER -> docker compose down
